DEFINE VARIABLE SELECTION AS CHAR FORMAT "X".
DEFINE SHARED VARIABLE XPROG AS LOGICAL.
REPEAT:
    FORM
                "                        OLD TYME SOLUTIONS             "
SKIP(0)
    "A.) GENERATE WEEKLY TICKETS"
SKIP(0)
    "B.) ENTER RETURNED TICKETS"
SKIP(0)
    "C.) ADD SINGLE TICKET"
SKIP(0)
    "D.) CHANGE SINGLE TICKET"
SKIP(0)
    "E.) DELETE SINGLE TICKET"
SKIP(0)
    "F.) REPRINT TICKET"
SKIP(0)
    "G.) GENERATE WEEKLY PAYROLL RPT"
SKIP(0)
    "H.) ROLLING VOLUME LIST by SUB & ROUTE"
SKIP(0)
    "I.) OUTSTANDING D/L TICKET REPORT"
SKIP(0)
    "J.) OUTSTANDING D/L by SUB & ROUTE"
SKIP(0)
    "K.) OUTSTANDING D/L by SUB & ROUTE (WEEKLY)"
SKIP(0)
    "L.) COMPLETED TICKET REPORT"
SKIP(0)
    "M.) --W-- STATUS TICKET REPORT"
SKIP(0)
    "N.) Upcoming Proposal Expiration"	
SKIP(2)
    "X.) EXIT"
        WITH CENTERED TITLE
        "W E E K L Y   T I C K E T   M A I N   M E N U   S C R E E N".
    UPDATE  SPACE(7) SELECTION AUTO-RETURN
        WITH SIDE-LABELS.
    HIDE.
        IF SELECTION = "A" THEN RUN WCRE.P.
   ELSE IF SELECTION = "B" THEN RUN WRET.P.
   ELSE IF SELECTION = "C" THEN RUN WADD.P.
   ELSE IF SELECTION = "D" THEN RUN WCHG.P.
   ELSE IF SELECTION = "E" THEN RUN WDEL.P.
   ELSE IF SELECTION = "F" THEN RUN WREP.P.
   ELSE IF SELECTION = "G" THEN RUN WPRO.P.
   ELSE IF SELECTION = "H" THEN RUN WRVSR.P.
   ELSE IF SELECTION = "I" THEN RUN WDLOUT.P.
   ELSE IF SELECTION = "J" THEN RUN WDLSUB.P.
   else if selection = "K" then run wdlwsub.p.
   ELSE IF SELECTION = "L" THEN RUN WCOMP.P.
   ELSE IF SELECTION = "M" THEN RUN WWOMP.P.
   ELSE IF SELECTION = "N" THEN RUN PropslExp.w.
   ELSE IF SELECTION = "X" THEN LEAVE.
   ELSE MESSAGE "INCORRECT CHOICE".
END.
