DEFINE SHARED VARIABLE XCOM AS INTEGER FORMAT "ZZ".
DEFINE SHARED VARIABLE XDIV AS INTEGER FORMAT "ZZ".
DEFINE SHARED VARIABLE XCOM-N AS CHAR FORMAT "X(30)".
DEFINE SHARED VARIABLE XDIV-N AS CHAR FORMAT "X(30)".
DEF SHARED VAR XOPR AS CHAR FORMAT "XXX".
DEF VAR XPROP AS DECIMAL FORMAT "ZZZZZZZZZZ".
DEF VAR XITEM AS DECIMAL FORMAT "ZZZZZZZZZZ".
DEF VAR XINV AS DECIMAL FORMAT "$->,>>>,>>>.99".
DEF VAR XDATE AS DATE FORMAT "99/99/9999".
DEF VAR S-TOT AS DECIMAL FORMAT "$->>>,>>>.99".
DEF VAR T-TOT AS DECIMAL FORMAT "$->>,>>>,>>>.99".
IF (USERID = "OPERATIONS") OR (USERID = "LANDMARK") OR (USERID = "GARCIA")
THEN DO:
    MESSAGE "YOU ARE NOT AUTHORIZED TO RUN THIS PROCEDURE".
    RETURN.
END.
S-TOT = 0.0.
T-TOT = 0.0.
OUTPUT TO PRINTER.
   FOR EACH INVOICE /*  USE-INDEX INDX1   */
                    WHERE INVOICE.COMP# = XCOM AND INVOICE.DIV# = XDIV AND
                          invoice.sub# = 0 and invoice.route# > 0 and
                          INVOICE.I-TYPE = "N" BREAK BY INVOICE.CUST#:
   FIND FIRST PROPSL /* USE-INDEX INDX  */
                 WHERE PROPSL.COMP# = INVOICE.COMP# AND
                       PROPSL.DIV# = INVOICE.DIV# AND
                       PROPSL.CUST# = INVOICE.CUST# AND
                       PROPSL.PROPSL# = INVOICE.PROPSL#.
   FORM HEADER TODAY FORMAT "99/99/9999"
               "INVOICE AUDIT REPORT" AT 30 "PAGE:" AT 65
               PAGE-NUMBER FORMAT ">>9" SKIP(1) XCOM-N SPACE(5) XDIV-N SKIP(1)
               "CUSTOMER #" AT 1 "CUSTOMER NAME" AT 15 "LOCATION NAME" AT 38
               SKIP(0) "PROPOSAL #" AT 1  "INDEX" AT 13
               "ITM" AT 19 "COMP-DATE" AT 24
               "AMOUNT" AT 42 "ORDER #" AT 54 "ORD ITM" AT 65
               SKIP(1) WITH FRAME P PAGE-TOP NO-LABELS NO-BOX.
   VIEW FRAME P.
   T-TOT = T-TOT + TOT-INV.
   IF FIRST-OF(INVOICE.CUST#)
       THEN DO:
           S-TOT = 0.0.
           DISPLAY SKIP(1) INVOICE.CUST# PROPSL.C-NAME PROPSL.L-NAME SKIP(0)
               INVOICE.PROPSL# SPACE(2) INVOICE.T-INDX SPACE(3)
               INVOICE.ITEM# INVOICE.C-DATE
               INVOICE.TOT-INV SPACE(3) INVOICE.ORD-NO SPACE(2) INVOICE.ITM-NO
               WITH FRAME A NO-BOX NO-LABELS.
           S-TOT = S-TOT + TOT-INV.
           NEXT.
       END.
   IF LAST-OF(INVOICE.CUST#)
       THEN DO:
           S-TOT = S-TOT + TOT-INV.
           DISPLAY INVOICE.PROPSL# SPACE(2) INVOICE.T-INDX SPACE(3)
           INVOICE.ITEM# INVOICE.C-DATE
           TOT-INV SPACE(3) INVOICE.ORD-NO SPACE(2) INVOICE.ITM-NO
           SKIP(0) SPACE(35) S-TOT "TOTAL" WITH FRAME B NO-BOX NO-LABELS.
           S-TOT = 0.0.
           NEXT.
       END.
       ELSE DO:
           DISPLAY INVOICE.PROPSL# SPACE(2) INVOICE.T-INDX SPACE(3)
                   INVOICE.ITEM# INVOICE.C-DATE
                   INVOICE.TOT-INV SPACE(3) INVOICE.ORD-NO SPACE(2)
                   INVOICE.ITM-NO WITH FRAME C NO-BOX NO-LABELS.
           S-TOT = S-TOT + TOT-INV.
       END.
   END.
   DISPLAY SKIP(2) SPACE(14) "ORDER TOTALS >>" T-TOT
       WITH FRAME D NO-LABELS NO-BOX.
