DEFINE SHARED VARIABLE XCOM AS INTEGER FORMAT "ZZ".
DEFINE SHARED VARIABLE XDIV AS INTEGER FORMAT "ZZ".
DEFINE SHARED VARIABLE XCOM-N AS CHAR FORMAT "X(30)".
DEFINE SHARED VARIABLE XDIV-N AS CHAR FORMAT "X(30)".
DEFINE SHARED VARIABLE XOPR AS CHAR FORMAT "XXX".
DEFINE VARIABLE XCUST AS DECIMAL FORMAT "ZZZZZZZZZZ".
DEFINE VAR XPROP AS DECIMAL FORMAT "ZZZZZZZZZZ".
DEF VAR XITEM AS INTEGER FORMAT "ZZZZ".
IF (USERID = "OPERATIONS") OR (USERID = "LANDMARK") OR (USERID = "GARCIA")
THEN DO:
    MESSAGE "YOU ARE NOT AUTHORIZED TO RUN THIS PROCEDURE".
    RETURN.
END.
REPEAT:
DISPLAY SPACE(13)
"I N V O I C E   D E S C R I P T I O N   S C R E E N         (CHG)"
SKIP(1)
    XCOM-N LABEL "CMP" SPACE(1)
    XDIV-N LABEL "DIV" SPACE(1)
    XOPR LABEL "OPR" SKIP(1).
    DISPLAY XCOM LABEL "COMPANY #" SPACE(5)
            XDIV LABEL "DIVISION #" SKIP(1).
    PROMPT-FOR ACCT-RCV.CUST#.
    XCUST = INPUT ACCT-RCV.CUST#.
    FIND FIRST ACCT-RCV WHERE ACCT-RCV.CUST# = XCUST AND
                              ACCT-RCV.COMP# = XCOM AND
                              ACCT-RCV.DIV# = XDIV AND
                              ACCT-RCV.C-STATUS <> "I" NO-ERROR.
    IF NOT AVAILABLE ACCT-RCV
    THEN DO:
       MESSAGE "CUSTOMER # "
         XCUST
         " DOES NOT EXISTS OR IS INACTIVE. TRY ANOTHER".
       UNDO, RETRY.
    END.
    DISPLAY ACCT-RCV.CUST# LABEL "CUSTOMER #" SPACE(5)
            ACCT-RCV.C-NAME LABEL "CUSTOMER NAME" SKIP(1).
    PROMPT-FOR AR-DESP.PROPSL#.
    XPROP = INPUT AR-DESP.PROPSL#.
    FIND FIRST PROPSL WHERE PROPSL.COMP# = XCOM AND PROPSL.DIV# = XDIV AND
                            PROPSL.CUST# = XCUST AND PROPSL.PROPSL# = XPROP
                            NO-ERROR.
    IF NOT AVAILABLE PROPSL
    THEN DO:
       MESSAGE "PROPOSAL # " XPROP " DOES NOT EXIST FOR THIS COMPANY/DIVISION".
       UNDO, RETRY.
    END.
    PROMPT-FOR AR-DESP.ITEM#.
    XITEM = INPUT AR-DESP.ITEM#.
    FIND FIRST PRO-DESP WHERE PRO-DESP.COMP# = XCOM AND
                              PRO-DESP.DIV# = XDIV AND
                              PRO-DESP.CUST# = XCUST AND
                              PRO-DESP.PROPSL# = XPROP AND
                              PRO-DESP.ITEM# = XITEM NO-ERROR.
    IF NOT AVAILABLE PRO-DESP
    THEN DO:
       MESSAGE "PROPOSAL/ITEM DOES NOT EXIST FOR THIS COMPANY/DIVISION".
       UNDO, RETRY.
    END.
    FIND FIRST AR-DESP WHERE AR-DESP.COMP# = XCOM AND AR-DESP.DIV# = XDIV AND
                       AR-DESP.CUST# = XCUST AND AR-DESP.PROPSL# = XPROP AND
                       AR-DESP.ITEM# = XITEM NO-ERROR.
    IF NOT AVAILABLE AR-DESP
    THEN DO:
        MESSAGE "THIS INVOICE ITEM DESCRIPTION DOES NOT EXIST".
        UNDO, RETRY.
    END.
    DISPLAY AR-DESP.PROPSL# LABEL "PROPOSAL #" SKIP(1)
            AR-DESP.ITEM# LABEL "ITEM #" SKIP(1)
            AR-DESP.DESC01 LABEL "DESCRIPTION"
               WITH SIDE-LABELS NO-BOX.
    UPDATE AR-DESP.DESC01 WITH COLOR DISPLAY NORMAL PROMPT W/MA.
    RELEASE AR-DESP.
END.
