DEFINE SHARED VARIABLE XCOM AS INTEGER FORMAT "ZZ".
DEFINE SHARED VARIABLE XDIV AS INTEGER FORMAT "ZZ".
DEFINE VAR BDATE AS DATE FORMAT "99/99/9999".
DEFINE VAR EDATE AS DATE FORMAT "99/99/9999".
DEFINE VAR NMO AS INTEGER FORMAT "ZZ".
DEF VAR BIRD-SONG AS LOGICAL
  LABEL "INCLUDE WEEKLY BALANCE AND TOTAL AMOUNT REMAINING ?".
IF (USERID = "OPERATIONS") OR (USERID = "LANDMARK") OR (USERID = "GARCIA")
THEN DO:
    MESSAGE "YOU ARE NOT AUTHORIZED TO RUN THIS PROCEDURE".
    RETURN.
END.
DISPLAY SPACE(7)
"W E E K L Y     --W--     T I C K E T   R E P O R T   S C R E E N"
SKIP(2) WITH NO-BOX SIDE-LABELS.
UPDATE BDATE LABEL "ENTER STARTING DATE RANGE" WITH NO-BOX SIDE-LABELS.
IF LASTKEY = KEYCODE("F4") OR LASTKEY = KEYCODE("ESC") THEN LEAVE.
UPDATE EDATE LABEL "ENTER ENDING DATE RANGE  " WITH NO-BOX SIDE-LABELS.
IF LASTKEY = KEYCODE("F4") OR LASTKEY = KEYCODE("ESC") THEN LEAVE.
OUTPUT TO PRINTER.
FOR EACH TICKET WHERE TICKET.COMP# = XCOM AND
                      TICKET.DIV# = XDIV AND
                      ticket.sub# = 0 and
                      ticket.route# > 0 and
                      T-STAT = "W" AND
                      (DATE-RET >= BDATE AND DATE-RET <= EDATE):
                                    /* BY TICKET.CUST#
                                    BY TICKET.DATE-RET: */
    FORM HEADER TODAY FORMAT "99/99/9999"
         "THE --W-- TICKET REPORT" AT 28 SKIP(1)
         "COMPANY" AT 20 TICKET.COMP# "DIVISION" AT 50 TICKET.DIV# SKIP(1)
         "FROM:" AT 20 BDATE "TO:" AT 40 EDATE SKIP(1).
FIND FIRST ACCT-RCV WHERE ACCT-RCV.COMP# = TICKET.COMP# AND
                    ACCT-RCV.DIV# = TICKET.DIV# AND
                    ACCT-RCV.CUST# = TICKET.CUST# AND
                    ACCT-RCV.C-STATUS <> "I".
IF NOT AVAILABLE ACCT-RCV THEN NEXT.
DISPLAY SKIP(0) ACCT-RCV.C-NAME SPACE(2)
              STRING(TICKET.COMP#, ">>") + "-" +
              TRIM(STRING(TICKET.DIV#, ">>")) + "-" +
              TRIM(STRING(TICKET.CUST#, ">>>>>>>>>>")) + "-" +
              TRIM(STRING(TICKET.PROPSL#, ">>>>>>>>>>")) + "-" +
              TRIM(STRING(TICKET.ITEM#, ">>>>")) + "-" +
              TRIM(STRING(TICKET.MONTH#, ">>")) + "-" +
              trim(string(ticket.wk#, ">")) + "-" +
              TRIM(STRING(T-INDX, ">>"))
                FORMAT "X(25)".
END.
